name: test_again

on: [workflow_dispatch, push, pull_request, issues, deployment_status]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use the output run ID and URL
        run: |
          echo ${{github.workflow_ref}}
          workflow_ref=${{github.workflow_ref}}
          echo "test1@test2" | awk -F "@" '{print $2}'
          echo $workflow_ref | awk -F "/" '{print $2}'
