name: test_again

on: [workflow_dispatch, push, pull_request, issues, deployment_status]

jobs:
  list_previous_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Get all workflow run ids
        id: get_runs
        run: |
          # Set the API endpoint to get all workflow runs for the current repository
          api_url="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
          
          # Fetch the workflow runs
          response=$(curl -s -H "Authorization: token ${{ secrets.token }}" "$api_url")

          # Parse the run_ids from the response
          run_ids=$(echo "$response" | jq -r '.workflow_runs[].id')

          # Output the list of run_ids
          echo "List of all run_ids: $run_ids"

          # Set run_ids as an output variable to be used in later steps
          echo "::set-output name=run_ids::$run_ids"

      - name: Show run_ids
        run: |
          echo "Previous run_ids: ${{ steps.get_runs.outputs.run_ids }}"


  #curl -u amansachdeva21:${{ secrets.token }} https://api.github.com/repos/amansachdeva21/workflow_validate/actions/workflows/${${{github.workflow_ref}} | awk -F "/" '{print $5}' | awk -F "@" '{print $1}'}
