name: test_again

on: [workflow_dispatch, push, pull_request, issues, deployment_status]

jobs:
  fetch-workflow-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get the workflow ID and run details
        run: |
          # Get the current workflow name (this is your workflow file name, e.g., 'CI')
          workflow_name="${{ github.workflow }}"
          
          # Define the API URL to list all workflow runs (this includes all run_ids under the workflow)
          api_url="https://api.github.com/repos/${{ github.repository }}/actions/workflows/${workflow_name}.yml/runs"

          # Fetch the list of runs for this workflow using GitHub API
          response=$(curl -s -H "Authorization: token ${{ secrets.token }}" "$api_url")
          
          # Extract the workflow ID (it's a part of the URL, so this uses the `workflow` name here)
          workflow_id=$(echo "$response" | jq -r '.workflow_runs[0].workflow_id')
          
          echo "Workflow ID: $workflow_id"
          
          # List all run IDs under this workflow
          run_ids=$(echo "$response" | jq -r '.workflow_runs[].id')

          echo "List of Run IDs under the workflow ID: $workflow_id"
          echo "$run_ids"
          
      - name: Display workflow info
        run: |
          echo "The workflow ID and run IDs are listed above."

  #curl -u amansachdeva21:${{ secrets.token }} https://api.github.com/repos/amansachdeva21/workflow_validate/actions/workflows/${${{github.workflow_ref}} | awk -F "/" '{print $5}' | awk -F "@" '{print $1}'}
