name: test_again

on: [workflow_dispatch, push, pull_request, issues, deployment_status]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use the output run ID and URL
        run: |
          #echo ${{github.workflow_ref}}
          workflow_ref=${{github.workflow_ref}} | awk -F "/" '{print $5}' | awk -F "@" '{print $1}'
          echo $workflow_ref
          #echo ${{github.workflow_ref}} | awk -F "/" '{print $5}' | awk -F "@" '{print $1}'
