name: Set Working Directory Based on User Input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  set-working-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Working Directory Based on Input
        working-directory: cloudrun/${{ github.event.inputs.environment }}
        run: |
          echo "Selected Working Directory: cloudrun/${{ github.event.inputs.environment }}"
          # Perform your actions here
          echo "Current directory: $(pwd)"
