name: Detect Cloud Run Folder Change

on:
  push:
    branches:
      - main
    paths:
      - "cloudrun/dev/**"
      - "cloudrun/prod/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    permissions:  # Needed for Workload Identity
      contents: write
      id-token: write
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Changed Folder
        id: check-folder
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^cloudrun/dev/'; then
            echo "WORKING_DIRECTORY=cloudrun/dev" >> $GITHUB_ENV
          elif git diff --name-only HEAD^ HEAD | grep -q '^cloudrun/prod/'; then
            echo "WORKING_DIRECTORY=cloudrun/prod" >> $GITHUB_ENV
          else
            echo "No relevant changes detected."
            exit 0
          fi

      - name: Print Detected Working Directory
        run: echo "Working Directory: $WORKING_DIRECTORY"
