name: User Input for Cloud Run Directory

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  detect-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Selected Environment
        run: |
          ${{ github.event.inputs.environment }}"
